# Сборка ---------------------------------------

# our local base image
FROM ubuntu:20.04 
LABEL description="Container for C++ build" 

# install build dependencies 
RUN apt-get update
RUN apt-get install -y rsync zip openssh-server  && \ 
    apt-get install -y build-essential apt-utils cmake  libboost-test-dev libspdlog-dev && \
    apt-get install -y byobu curl git htop man unzip vim wget




